config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :jobs do
    resources :applications, except: :index
  end

  get 'applications' => 'applications#index', as: :applications
  
  devise_scope :admin do
    get "/admin" => "devise/sessions#new"
  end

  root to: 'home#index'
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application.rb
class Application < ActiveRecord::Base
  mount_uploader :resume, ResumeUploader
  mount_uploader :coverletter, CoverletterUploader

  belongs_to :job
  after_initialize :set_status

  validates :name, length: { minimum: 5 }, presence: true
  validates :email, length: { minimum: 10 }, presence: true
  validates :phone,:resume,:coverletter, presence: true

  default_scope { order('created_at DESC') }
  scope :fresh, -> { where(status: 'New Application') } 
  scope :review, -> { where(status: 'Under Review') } 
  scope :rejected, -> { where(status: 'Rejected') } 
  scope :hired, -> { where(status: 'Hired') } 

  extend FriendlyId
  friendly_id :name, use: :slugged
  
  def set_status
    self.status="New Application"
  end
end

app/models/job.rb
class Job < ActiveRecord::Base
  has_many :applications, dependent: :destroy

  validates :title, length: { minimum: 5 }, presence: true
  validates :description, length: { minimum: 50 }, presence: true
  
  default_scope { order('created_at DESC') }
  
  extend FriendlyId
  friendly_id :title, use: :slugged
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception

  rescue_from Pundit::NotAuthorizedError do |exception|
     redirect_to root_url, alert: "You are not allowed to access this."
   end

  def pundit_user
    current_admin
  end
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  def index
    @fresh=Application.fresh
    @review=Application.review
    @rejected=Application.rejected
    @hired=Application.hired

    authorize @fresh
  end

  def new
    @application=Application.new
    authorize @application
  end

  def create
    @job=Job.friendly.find(params[:job_id])
    @application=@job.applications.build(application_params)
    authorize @application

    if @application.save
      flash[:notice]= "Congratulations! You have successfully submitted an application."
      redirect_to @job
    else
      flash[:error]= "There was an error in submitting your application. Please try again."
      render 'jobs/show'
    end
  end

  def show
    @application=Application.friendly.find(params[:id])
    @job=@application.job
    authorize @application
  end

  def update
    @application=Application.friendly.find(params[:id])
    @job=Job.friendly.find(params[:job_id])
    authorize @application

    if @application.update_attributes(application_params)
      flash[:notice]= "Application was successfully updated."
      redirect_to [@job,@application]
    else
      flash[:error]= "There was an error in updating the application."
      render :show
    end
  end

  private

  def application_params
    params.require(:application).permit(:name,:phone,:email,:status,:resume,:coverletter,:notes)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
    @jobs=Job.all
  end

  def show
    @job=Job.friendly.find(params[:id])
    @application=Application.new
    @errors=@application.errors
  end

  def new
    @job=Job.new
    authorize @job
  end

  def create
    @job=Job.new(params.require(:job).permit(:title,:description))
    authorize @job

    if @job.save
      flash[:notice]= "Job was successfully listed."
      redirect_to @job
    else
      flash[:error]= "There was an error in creating the job."
      render :new
    end
  end

  def edit
    @job=Job.friendly.find(params[:id])

    authorize @job
  end

  def update
    @job=Job.friendly.find(params[:id])
    authorize @job

    if @job.update_attributes(params.require(:job).permit(:title,:description))
      flash[:notice]= "Job was successfully listed."
      redirect_to @job
    else
      flash[:error]= "There was an error in updating the job."
      render :edit
    end
  end

  def destroy
    @job =Job.friendly.find(params[:id])
    authorize @job

     title = @job.title
 
     if @job.destroy
       flash[:notice] = "The listing for \"#{title}\" was deleted successfully."
       redirect_to jobs_path
     else
       flash[:error] = "There was an error deleting the listing."
       render :show
     end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def form_group_tag(errors, &block)
     if errors.any?
       content_tag :div, capture(&block), class: 'form-group has-error'
     else
       content_tag :div, capture(&block), class: 'form-group'
     end
   end
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/applications/_admin.html.erb
<%=form_for [job,application] do |f| %>
  <p><b>Current Status:</b> <%=application.status%></p>
  <div class="form-group">
      <%= f.label "Update Status" %>
      <%= f.select(:status,["New Application","Under Review","Rejected","Hired"])%>
  </div>
  <div class="form-group">
      <%= f.label "Admin Notes" %>
      <%= f.text_area :notes, rows: 8, class: 'form-control', placeholder: "Enter job description" %>
  </div>
  <div class="form-group">
    <%= f.submit "Update Admin Section", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/applications/_application.html.erb
<div class="col-md-12">
  <h4 class="inline"><%=link_to application.name, [application.job, application]%></h4> 
  <h6 class="inline"> for <%=application.job.title%></h6>
  <small>submitted on <%=application.created_at.strftime("%B %d at %l %p %Z") %></small>
</div>

app/views/applications/_form.html.erb
<%=form_for [job,application] do |f| %>
  <% if application.errors.any? %>
    <div class="alert alert-danger">
      <h4>There are <%= pluralize(application.errors.count, "error") %></h4>
      </ul>
        <%application.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <%end%>
      </ul>
    </div>
  <%end%>
  <%= form_group_tag(application.errors[:name]) do %>
    <%= f.label "Name*"%>
    <%= f.text_field :name, class: 'form-control', placeholder: "Enter your Full Name" %>
  <% end %>
  <%= form_group_tag(application.errors[:phone]) do %>
    <%= f.label "Phone*"%>
    <%= f.text_field :phone, class: 'form-control', placeholder: "Enter your Phone Number" %>
  <% end %>
  <%= form_group_tag(application.errors[:email]) do %>
    <%= f.label "Email*"%>
    <%= f.text_field :email, class: 'form-control', placeholder: "Enter your email Address" %>
  <% end %>
  <div class="form-group">
         <%= f.label "Resume (Formats: pdf, doc, docx)*" %>
         <%= f.file_field :resume %>
  </div>
   <div class="form-group">
         <%= f.label "Cover letter (Formats: pdf, doc, docx)*"%>
         <%= f.file_field :coverletter %>
  </div>
  <div class="form-group">
    <%= f.submit "Submit", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/applications/index.html.erb
<div class="row">
  <h1>Applications</h1>
  <div class="col-md-12">
   <ul class="nav nav-tabs">
    <li class="active"><a data-toggle="tab" href="#new">New</a></li>
    <li><a data-toggle="tab" href="#review">Under Review</a></li>
    <li><a data-toggle="tab" href="#rejected">Rejected</a></li>
    <li><a data-toggle="tab" href="#hired">Hired</a></li>
</ul>

<div class="tab-content">
  <div id="new" class="tab-pane fade in active">
   <%=render @fresh%>
  </div>
  <div id="review" class="tab-pane fade">
     <%=render @review%>
  </div>
  <div id="rejected" class="tab-pane fade">
    <%=render @rejected%>
  </div>
   <div id="hired" class="tab-pane fade">
    <%=render @hired%>
  </div>
</div>
   </div>
 </div>

app/views/applications/new.html.erb
<h1>Applications#new</h1>
<p>Find me in app/views/applications/new.html.erb</p>

app/views/applications/show.html.erb
<div class="row">
  <div class="col-md-12">
      <a><%= link_to "Back to all Applications",applications_path, class: 'btn btn-cta-secondary btn-small' %></a>
  </div>
  <div class="col-md-8">
    <h1><%=@application.name%></h1>
    <p><b>Position:</b> <%=@application.job.title%></p>
    <p><b>Phone:</b> <%=@application.phone%></p>
    <p><b>Email:</b> <%=@application.email%></p>
    <a href="<%=@application.resume%>" target="blank" class="btn btn-lg">
      <i class="fa fa-download"></i> Download Resume
                    </a>
    <a href="<%=@application.coverletter%>" target="blank" class="btn btn-lg">
        <i class="fa fa-download"></i> Download Coverletter
                    </a>
  </div>
  <div class="col-md-4">
    <h3>Admin Section</h3>
    <%= render partial: 'admin', locals: {job:@job, application:@application}%>
  </div>
</div>

app/views/home/index.html.erb
<body data-spy="scroll">
    
    <!-- ******PROMO****** -->
    <section id="promo" class="promo section offset-header">
        <div class="container text-center">
            <h2 class="title">Hired<span class="highlight">!</span></h2>
            <p class="intro">The Leading Westerosi Job Board</p>
            <div class="btns">
                <a class="btn btn-cta-secondary" <%= link_to "Find a Job", jobs_path%></a>
            </div>
        </div><!--//container-->
        <div class="social-media">
            <div class="social-media-inner container text-center">
                <ul class="list-inline">
                    
        
                </ul>
            </div>
        </div>
    </section><!--//promo-->
    
    <!-- ******ABOUT****** --> 
    <section id="about" class="about section">
        <div class="container">
            <h2 class="title text-center">What is Hired!?</h2>
            <p class="intro text-center">Hired! is a compilation of jobs from all across Westeros: from the Wall to King's Landing.  We are the leading job board for companies, candidates and wildlings.  Whether you are looking for a managment position or to fight white walkers, we have something for you. </p>
            <div class="row">
                  
            </div><!--//row-->            
        </div><!--//container-->
    </section><!--//about-->

app/views/jobs/_form.html.erb
<%= form_for job do |f| %>
  <% if job.errors.any? %>
    <div class="alert alert-danger">
      <h4>There is <%= pluralize(job.errors.count, "error") %></h4>
      </ul>
        <%job.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <%end%>
      </ul>
    </div>
  <%end%>
    <%= form_group_tag(job.errors[:title]) do %>
      <%=f.label :title %>
      <%= f.text_field :title, class: 'form-control', placeholder: "Enter job title" %>
    <%end%>
    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description, rows: 8, class: 'form-control', placeholder: "Enter job description" %>
    </div>
    <%= f.submit "Save", class: 'btn btn-success' %>
  <% end %>
</div>

app/views/jobs/_job.html.erb
<div class="col-md-4">
  <h4><%=link_to job.title, job%></h4><i><small>posted on <%=job.created_at.strftime("%B %d") %></small></i>
</div>
<div class="col-md-8">
  <%if current_admin.present?%>
    <span><%= link_to "Edit", edit_job_path(job), class: 'badge inline' %></span>
  <%end%>
</div>
<div class="col-md-12">
  <p><%=job.description%></p>
</div>

app/views/jobs/destroy.html.erb
<h1>Jobs#delete</h1>
<p>Find me in app/views/jobs/delete.html.erb</p>

app/views/jobs/edit.html.erb
<div class="row">
  <h1>List a New Job</h1>
  <div class="col-md-4">
     <p>Guidelines for Listings:</p>
     <ul>
       <li>Title must be longer than 10 characters.</li>
       <li>Description must be longer than 144 characters.</li>
     </ul>
   </div>
   <div class="col-md-8">
      <%= render partial: 'form', locals: { job: @job} %>
  </div>
</div>

app/views/jobs/index.html.erb
<div class="row">
  <h1>Jobs</h1>
  <div class="col-md-12">
   </div>
  <div class="col-md-8">
    <%=render @jobs%>
  </div>
  <div class="col-md-4">
    <%if current_admin.present?%>
      <%= link_to "New Job Listing", new_job_path, class: 'btn btn-success' %>
    <%end%>
  </div>
</div>

app/views/jobs/new.html.erb
<div class="row">
  <h1>List a New Job</h1>
  <div class="col-md-4">
     <p>Guidelines for New Listings:</p>
     <ul>
       <li>Title must be longer than 10 characters.</li>
       <li>Description must be longer than 144 characters.</li>
     </ul>
   </div>
   <div class="col-md-8">
      <%= render partial: 'form', locals: { job: @job} %>
  </div>
</div>

app/views/jobs/show.html.erb
<div class="row">
  <div class="col-md-12">
      <a><%= link_to "Back to all Jobs",jobs_path, class: 'btn btn-cta-secondary btn-small' %></a>
   </div>
  <div class="col-md-12"><h1><%=@job.title%></h1></div>
  <div class="col-md-8">
    <p><%=@job.description%></p>
    </br>
    <h3>Apply for the Position</h3>
    <%= render partial: 'applications/form', locals: {job:@job, application:@application}%>
  </div>
  <div class="col-md-4">
    <%if current_admin.present?%>
   <%= link_to "Edit Listing", edit_job_path(@job), class: 'btn btn-success' %>
    <%= link_to "Delete Listing", @job, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this listing?' } %> 
    <%end%>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hired</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Lato:300,400,300italic,400italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'> 
</head>
<body>
 <!-- ******HEADER****** --> 
  <header id="header" class="header">  
    <div class="container">  
      <nav id="main-nav" class="main-nav navbar-left" role="navigation">
        <div class="navbar-header">
          <div class="navbar-collapse collapse" id="navbar-collapse">
             <ul class="nav navbar-nav">
                <li class="active nav-item sr-only" <%= link_to "Home", root_path, method: :get %></li>
                <li class="nav-item"><a class="scrollto"<%= link_to "Home", root_path,method: :get %></a></li>
                <li class="active nav-item sr-only" <%= link_to "Jobs", jobs_path, method: :get %></li>
                <li class="nav-item"><a class="scrollto"<%= link_to "Jobs", jobs_path,method: :get %></a></li>
                <%if current_admin.present?%>
                <li class="active nav-item sr-only" <%= link_to "Manage Applications", applications_path, method: :get %></li>
                <li class="nav-item"><a class="scrollto"<%= link_to "Manage Applications", applications_path,method: :get %></a></li>
                <%end%>
              </ul>
            </div>
          </div>
        </nav>
        <nav id="main-nav" class="main-nav navbar-right" role="navigation">
          <div class="navbar-header">
            <div class="navbar-collapse collapse" id="navbar-collapse">
              <ul class="nav navbar-nav">
                <% if current_admin %>
                <li class="nav-item greeting inline">
                   Hello Admin! </li>
                <li class="nav-item inline"><%= link_to "Sign out", destroy_admin_session_path, method: :delete %>
                </li>
                <% end %>
              </ul>
            </div><!--//navabr-collapse-->
          </div>
        </nav>
      </div>
  </header>
<div class="page">
  <div class="col-md-12">
       <% if flash[:notice] %>
         <div class="alert alert-success">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:notice] %>
         </div>
       <% elsif flash[:error] %>
         <div class="alert alert-danger">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:error] %>
         </div>
       <% elsif flash[:alert] %>
         <div class="alert alert-warning">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:alert] %>
         </div>
       <% end %>
     </div>
<%= yield %>
</div>
</body>
</html>